#!/usr/bin/env sh

# @TODO migrate this to go so we can parse a yaml/json/hcl config?

(
    BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    ROOT_DIR="$( cd "$( dirname "${BIN_DIR}" )" >/dev/null 2>&1 && pwd )"
    CONFIG_DIR="$( cd "${ROOT_DIR}/config" >/dev/null 2>&1 && pwd )"
    SRC_DIR="$( cd "${ROOT_DIR}/src" >/dev/null 2>&1 && pwd )"

    if [ -s $CONFIG_DIR/dist.env ]; then
        eval $(cat $CONFIG_DIR/dist.env)
    fi

    if [ -s $CONFIG_DIR/.env ]; then
        eval $(cat $CONFIG_DIR/.env)
    fi

    GIT_TAGS=( $(git log -n1 --pretty="format:%d" 2>/dev/null | tr ',' '\n' | grep tag: | sed 's/ tag: //g' | sed 's/)$//g') )
    GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null)
    GO_VERSION="$(go version | sed 's/go//g' | tr ' ' '\n' | grep '\d\+.\d\+.\d\+')"
    BUILT_DATE="$(date)"
    BUILD_OS="$(go env GOHOSTOS)"
    BUILD_ARCH="$(go env GOHOSTARCH)"
    
    cd "${SRC_DIR}" && go run -ldflags "
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.name=${APPLICATION_NAME:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.short=${SHORT_DESCRIPTION:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.long=${LONG_DESCRIPTION:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.version=${GIT_TAGS[0]:-dev}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.gitVersion=${GIT_COMMIT:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.goVersion=${GO_VERSION:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.buildDate=${BUILT_DATE:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.buildOS=${BUILD_OS:-unknown}'
        -X 'github.com/jamesthomasonjr/golang-cli-skeleton/version.buildArch=${BUILD_ARCH:-unknown}'
    " main.go "$@"
)
